---
    platform: linux
    inputs:
      - name: node_poc 
    image_resource:
      type: docker-image
      source: {repository: node}
    run:  
      path: /bin/sh
      args:
        - -c
        - |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          ls -l
          pwd
          ls /
          ls -l ../
          ls -l ../../
          npm install
          npm test