---
    platform: linux
 
    image_resource:
      type: docker-image
      source: {repository: node}
    run:
      inputs:
        - name: node_poc   
      path: /bin/sh
      args:
        - -c
        - |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          npm install
          npm test