---
    platform: linux
    inputs:
      - name: node_poc 
    image_resource:
      type: docker-image
      source: {repository: node}
    run:  
      path: /bin/sh
      args:
        - -c
        - |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          echo registry=https://art-bobcat.autodesk.com/artifactory/api/npm/autodesk-npm-virtual/  > ~/.npmrc
          echo @adsk:registry=https://art-bobcat.autodesk.com/artifactory/api/npm/autodesk-npm/ >> ~/.npmrc
          cd node_poc
          npm install
          npm test